apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
#    traefik.frontend.rule.type: PathPrefixStrip
  creationTimestamp: null
  name: metrics-demo
  namespace: dev
spec:
  rules:
  - host: training-user-18.training.weave.works
    http:
      paths:
      - backend:
          serviceName: metrics-demo
          servicePort: 3000
        path: /metrics-demo
  tls:
  - hosts:
    - training-user-18.training.weave.works
    secretName: ingress-certificate
status:
  loadBalancer: {}
